# crates/sinter-plugins/Cargo.toml
[package]
name = "sinter-plugins"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sinter = { path = "../sinter-core" }
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
