[package]
name = "helloworld"
version = "0.1.0"
main = "Main"
scala_version = "2.13"
source_dir = "src/main/scala"
target_dir = "target"
test_dir = "src/test/scala"
backend = "scala-cli"

[dependencies]